name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Assuming you have a test directory or test files
          pytest  # or your preferred testing command

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the build job completes successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Set your Heroku API key in GitHub secrets
        run: |
          git remote add heroku https://git.heroku.com/YOUR_HEROKU_APP_NAME.git
          git push heroku main  # Change 'main' if needed
